### PR TITLE
Added settings file to example, minor changes in the slingshot.js file

### PR DESCRIPTION
**Pull request by JuanCrg90**
Hi, i added a settings file for your example and  added a comment in the bucket name, i hope you can to consider my change.

I found some JSHint warnings in the package. can i update that?

### CODE REVIEW

**Comment by jamgold** [comment]
[edit] I think we should only check in example/.meteor/packages. I like the settings.js you added, but the format changes I find unnecessary.

**Comment by JuanCrg90** [comment]
I added example/.meteor because i received this message

captura de pantalla de 2015-08-01 13-44-42

You recommend remove all files in .meteor except .meteor/release?

**Comment by jamgold** [comment]
Interesting. The original example directory has a .meteor but only the packages file in it. I wonder why I never saw that message. I guess release is ok, but the id file shouldn't be there, neither the versions.

**Comment by JuanCrg90** [comment]
Then I remove:
- .meteor / .id
- .meteor / Versions

And I send a new commit?

**Comment by jamgold** [comment]
What about all the changes where just the indent of { seemed moved?

**Comment by JuanCrg90** [comment]
I applied auto indentation in my editor, i suppose some comment line caused a bad indentation.

mmm.Iif you want, better cancel the pull request and add the release file, in your master branch, really its a minimal change.

Regards :smile:

**Comment by jamgold** [comment]
I will do that. Thank you for submitting the change

**Pull request closed without merging**
